// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiut-LkD_b6o_SP-ChmnOpRVSCHFfC7vE',
    appId: '1:1087824252092:web:606db952cc21c6dbf794b9',
    messagingSenderId: '1087824252092',
    projectId: 'nirvaan-74ff2',
    authDomain: 'nirvaan-74ff2.firebaseapp.com',
    storageBucket: 'nirvaan-74ff2.firebasestorage.app',
    measurementId: 'G-V4LZLYYHB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_MOLaYU80kP58GZNoc274QXLDPZVRTk8',
    appId: '1:1087824252092:android:a72811dfc7adf2e6f794b9',
    messagingSenderId: '1087824252092',
    projectId: 'nirvaan-74ff2',
    storageBucket: 'nirvaan-74ff2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlFTz2XXaq7YKGz0OXhTBJjP9Xv6e0ghM',
    appId: '1:1087824252092:ios:06e22ba12f3be2b5f794b9',
    messagingSenderId: '1087824252092',
    projectId: 'nirvaan-74ff2',
    storageBucket: 'nirvaan-74ff2.firebasestorage.app',
    iosBundleId: 'com.example.nirvaan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlFTz2XXaq7YKGz0OXhTBJjP9Xv6e0ghM',
    appId: '1:1087824252092:ios:06e22ba12f3be2b5f794b9',
    messagingSenderId: '1087824252092',
    projectId: 'nirvaan-74ff2',
    storageBucket: 'nirvaan-74ff2.firebasestorage.app',
    iosBundleId: 'com.example.nirvaan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiut-LkD_b6o_SP-ChmnOpRVSCHFfC7vE',
    appId: '1:1087824252092:web:471583a137cf67faf794b9',
    messagingSenderId: '1087824252092',
    projectId: 'nirvaan-74ff2',
    authDomain: 'nirvaan-74ff2.firebaseapp.com',
    storageBucket: 'nirvaan-74ff2.firebasestorage.app',
    measurementId: 'G-SRGY1G9NMG',
  );
}
